# Generated by Django 3.2.7 on 2021-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_telegramm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
