# Generated by Django 3.2.7 on 2022-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220122_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_telegram',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ID_Телеграм'),
        ),
        migrations.AlterField(
            model_name='project',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя Телеграм'),
        ),
    ]
