# Generated by Django 3.2.7 on 2022-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220122_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_author',
            field=models.BooleanField(default=False, verbose_name='Показывать Автора'),
        ),
    ]
